### ISSUE TITLE
order not clear, when running a directory containing rml files

### ISSUE THREAD

**Issue by treegardel** [hz-b/rayx#118]
As a user, I would expect the RML files to be processed in alphabetical order. For me it looks like a random order, even after I "touched" them all one after the other:

Here is the screenshot of my directory:
![image](https://user-images.githubusercontent.com/103497430/199942391-295cbd80-fecb-401f-a703-c29070269015.png)

By the order of the h5 files you can see in which order the files were processed.

A nice feature would be to display the file that is being traced in the terminal. It is displayed in -V mode, but then so many more things are displayed.

**Comment by memoryleak47** [comment]
fixed in 209b7e7.

**Comment by treegardel** [comment]
I just tested it - I see the filename, but the order is still random. Didn't we want to change this so that the files are at least processed alphabetically?

**Comment by Atraxus** [comment]
RAY-X traces files in a directory in alphabetical order for me. @treegardel, could you check again if this behavior persists?
