### ISSUE TITLE
Tracing on Vulkan does not support empty beamlines

### ISSUE THREAD

**Issue by OSMaxwell** [hz-b/rayx#140]
If Beamline is empty, quadric buffer (Elements' meta-data) will also be empty. 
This case is a testcase, in which we only test MatrixSource (RML with only source)

Consequence: Vulkan can't create/allocate 0-sized buffers.

Temporary solution: A dummy Plane is added to the RML with [0,0] size. 

This feature might become handy later on. So keep it in mind that for now `vector<opticalElement>.size()` has to be `!= 0`

**Comment by EnricoAhlers** [comment]
Waiting for SYCL decision

**Comment by Atraxus** [comment]
Is this still an issue? Why do we need to trace empty beamlines?

**Comment by EnricoAhlers** [comment]
This was literally 2 lines of code. Good thing we had this ticket for 9 months :D
