### ISSUE TITLE
h5 export options

### ISSUE THREAD

**Issue by pforson** [hz-b/rayx#153]
Currently we are exporting 'everything', but in most use cases only a small subset is required. Export options would be super. 

Use Case Multi-RZP:
Desired columns: ["Xloc", "Yloc", "Energy"]

I want to save a h5 file using gzip compression:
```
with h5py.File(export, 'w') as f:
    f.create_dataset("X", data=Xloc, compression="gzip")
    f.create_dataset("Y", data=Yloc, compression="gzip")
    f.create_dataset("EN", data=Energy, compression="gzip")
```

**Comment by memoryleak47** [comment]
This is now supported using the `-F` or `--format` option.
It allows you to specify which components of the Rays you like to export to H5/CSV.
Example usage: `-F "X-position|Y-position[Energy|Weight"`

To see all potential formatting options, use `-F help` or any invalid format.
