### ISSUE TITLE
collision normal sometimes points into the wrong direction; this causes problems in the RZP.

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/rayx#172]

**Comment by memoryleak47** [comment]
In 7130ba63, we improved the hotfix to a rather general solution for all collisions. So now the normal points to the right direction.

Still, it would be faster and more idiomatic to have each collision type already generate the normal in the right direction.
Concretely the Quadric seems to be faulty as of now.

**Comment by Atraxus** [comment]
There is a todo in the code for a later rework of the hotfix
