### ISSUE TITLE
RZP alignment issue

### ISSUE THREAD

**Issue by pforson** [hz-b/rayx#180]
**Describe the bug**
When tracing an RZP (planar or spherical) the traced result matches RAY-UI and experiment data in the case where no misalignment takes place. If misalignment is applied the resulting detector images are incorrect. This occurs not only when tracing multi-RZPs, but also regular single-RZPs.

**To Reproduce**
I will produce a few rmls which demonstrate this issue and add them here.

**Expected behavior**
I will produce plots which show the incorrect behaviour and the correct behaviour.

**Screenshots**
RAY-X (misalignment branch) - single RZP of a multi-RZP
RAY-UI (Version: git-385-g5494f9ac) - single RZP of a multi-RZP
Real Experiment Data - Multi-RZP (multiples of the singles which were simulated)

All examples with an offset of -0.5mm in the x-axis.

RAY-X:
![test_singleRZP_widePointSource_x-0_5](https://github.com/hz-b/rayx/assets/10009675/2a2625f0-1154-41d5-b155-2c22ec516cad)

RAY-UI:
![test_singleRZP_widePointSource_x-0_5_rayui](https://github.com/hz-b/rayx/assets/10009675/10700592-63cc-4129-9a83-281d431756db)

Real:
![test_multiRZP_widePointSource_x-0_5_real](https://github.com/hz-b/rayx/assets/10009675/ea0b61d4-fe3b-4603-b1d4-817b468e1430)

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - CPU or Quadro T1000 GPU

**Additional context**
This fix is required for the Master Thesis of Enrico and therefore should have a high priority

**Comment by memoryleak47** [comment]
I think the last state on this issue was, that we were waiting for you to test translational misalignment on the misalignment-rzp branch from a few weeks ago.

**Comment by treegardel** [comment]
To be able to work on this further, we definitely need real-world results as well: x-translation scan of a plan single RZP and the camera image. With this, we first have to see whether RAY-UI calculates correctly. @pforson do you have such data from your measurements?

**Comment by pforson** [comment]
Yes I have this experiment data. I'll try and compile everything as best I can to demonstrate the issue and update.

**Comment by Atraxus** [comment]
@pforson and @treegardel will meet and discuss this further

**Comment by pforson** [comment]
updated the original issue with screenshots - My opinion is that the change we made to RAY-X has not worked and it should be reverted back to the current RAY-UI method.

However - RAY-UI is also not correct as the Mn part only ever changes shape perfectly horizontally, which is incorrect.

**Comment by treegardel** [comment]
@pforson please can you also add the rml-files for both cases, or a link if they are in another issue already? And do you also have a real case picture with no translation error?

**Comment by pforson** [comment]
@treegardel I can't upload the rmls here (unsupported file format). I will upload in Mattermost.
Other examples, including a case with no translation error are in mattermost (dev channel).

**Comment by treegardel** [comment]
[test_singleRZP.zip](https://github.com/hz-b/rayx/files/12752296/test_singleRZP.zip)
@pforson is it possible to transform the pixel units into mm in the real picture? (only for a "rough" estimation if this fits somehow)

**Comment by pforson** [comment]
![test_singleRZP_widePointSource_x-0_5](https://github.com/hz-b/rayx/assets/10009675/978db50a-9b34-4675-a918-532ab50fc551)

RAY-X development branch - looks like RAY-UI. This is closer to the the reality than the changes that were implemented in the misalignement-rzp branch. Therefore this branch should not be merged into development.

Further modifications to attempt to make the trace look more like the experiment images will be discussed.

**Comment by pforson** [comment]
Tested and with an offset in the Z-axis traces equivalent to Ray-UI. This feature is currently in use and if any issues arise I will re-open.
