### ISSUE TITLE
XY XZ Plane incosistency

### ISSUE THREAD

**Issue by Atraxus** [hz-b/rayx#189]
Currently, some elements lie in the XY plane (ImagePlane / Slit), while the rest lies in the XZ plane.
We are considering unifying this into one of the two planes, and representing the y-z rotation using the inTrans & outTrans.

**Comment by memoryleak47** [comment]
As of commit 70070e474593c169501df1cd1e4566169dc3121d, we have fixed the XZ as primary plane inside of our model.
