### ISSUE TITLE
Rendering issue toroid

### ISSUE THREAD

**Issue by Atraxus** [hz-b/rayx#197]
**Describe the bug**
When rendering the toroid beamline, the rays or the toroid are not placed correctly. Further not all rays seem to be renderd

**To Reproduce**
1. Open rayx-ui
2. Load this rml file 
[zippy.zip](https://github.com/hz-b/rayx/files/12909843/zippy.zip)
3. Go to the toroid optical element

**Expected behavior**
The rays should hit the object and no orange rays should just end without another bounce

**Screenshots**
<img width="1537" alt="image" src="https://github.com/hz-b/rayx/assets/13185253/d8d973c8-a86a-4e9f-8fea-209083919a0c">

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Atraxus** [comment]
@memoryleak47, do you know why some rays are reflected by the toroid (marked red) and some run out of bounces (marked pink). The rays that run out of bounces are (temporarily) rendered in white here
<img width="1589" alt="image" src="https://github.com/hz-b/rayx/assets/13185253/051cd0e0-9644-4574-9604-c664f5175f7d">

**Comment by memoryleak47** [comment]
@Atraxus

> do you know why some rays are reflected by the toroid (marked red) and some run out of bounces (marked pink). The rays that run out of bounces are (temporarily) rendered in white here.

Yes, this is what I described in the meeting last week. Due to an imprecision in the Toroid collision, some rays repeatedly collide with the toroid until they are out of bounces.

This was fixed in ad5329d, the zip file contains rays from an older version.

**Comment by Atraxus** [comment]
Fixed with 7105f4ec8ce9a792b6a33482f51c95229039ca03
