### ISSUE TITLE
benchmark.py doesn't work (on linux)

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/rayx#198]
I've tried using bechmark.py and identified the following problems:
- it tries to use an executable named rayx.exe that doesn't exist on linux
- It cannot be called from the Scripts directory, instead you need to be in the repository root and call it as `python Scripts/benchmark.py`
- path_to_input looks for a directory named "scripts" and not "Scripts" (how did this ever work for anyone? is windows case insensitive?)
- what even is this output:
```
,Value
CPU model,x86_64
CPU cores,8
Total RAM,5.74GB
GPU model,No GPU found
Total GPU memory,N/A
```

It doesn't even show the time it took. (Should I run this within `time`?)

**Comment by EnricoAhlers** [comment]
The instrumentor currently doesn't work at all on development and needs to be fixed first. Then we can fix the benchmark function for Linux.

**Comment by Atraxus** [comment]
TODO: decide to do benchmarking during runtime and remove json functionality

**Comment by EnricoAhlers** [comment]
Benchmarking works now on Ubuntu

**Comment by EnricoAhlers** [comment]
I got very interesing results:
<img width="942" alt="image" src="https://github.com/hz-b/rayx/assets/4237050/18939074-d4d8-4e1b-9e6c-95531a47caad">

**Comment by EnricoAhlers** [comment]
Needs further testing to see whether the OS or the compiler makes such a difference.

**Comment by memoryleak47** [comment]
@EnricoAhlers just fixed the aforementioned issues. Thanks!
