### ISSUE TITLE
rayx-ui crashes on startup if PWD != build/bin/debug

### ISSUE THREAD

**Issue by memoryleak47** [hz-b/rayx#199]
If you start rayx-ui and your working directory is not in the build/bin/debug (or build/bin/release directory), it fails on startup with "failed to open file!".
Probably, because it doesn't find some shader file whose path is given relative.
In rayx, we use CanonicalizePath for to solve these problems.

**Comment by Atraxus** [comment]
Fixed with 6e9dedf81c8428575a5abf1f5b47e08e6dde49d6
