### ISSUE TITLE
move camera between elements?

### ISSUE THREAD

**Issue by EnricoAhlers** [hz-b/rayx#204]
RAYX-UI needs a list or buttons or an extra new Imgui window to help navigate the camera between optical elements.

More about this
The option should support object grouping (RZP) and look comfortable and readable enough for beamlines that contain many objects.

**Comment by Atraxus** [comment]
Currently the look-at function is not leading to an intuitive behavior, when clicking on beamline elements.

**Comment by EnricoAhlers** [comment]
<img width="687" alt="image" src="https://github.com/hz-b/rayx/assets/4237050/47fad15b-93d6-4318-a1f3-03f579b9a290">
