### ISSUE TITLE
Image Footprint Texture on RAYX-UI Elements

### ISSUE THREAD

**Issue by EnricoAhlers** [hz-b/rayx#210]
It would be nice to display the generated footprint on each rendered element.

**Comment by EnricoAhlers** [comment]
After considering the gains vs complexity I've come to the conclusion that we should not yet implement such a feature using VULKAN.

**Comment by Atraxus** [comment]
I will be implementing this, since the priority increased.

**Comment by Atraxus** [comment]
- [ ] Bugfix loading image data instead of saved file
- [ ] Save file as png
- [ ] Better binning?
- [ ] Better color scheme for value scale

**Comment by Atraxus** [comment]
Future work:
- Optimal Binning (https://stats.stackexchange.com/a/862 https://gnpalencia.org/optbinning/)
- Iterative binning (focus on interesting areas)

**Comment by Atraxus** [comment]
Done for quadrilaterals
