### ISSUE TITLE
Missing Source: Simple Undulator

### ISSUE THREAD

**Issue by treegardel** [hz-b/rayx#224]
This source is used for simulating a Undulator source in a very simple way: it is a point source whose quantities (source size and divergence) are calculated from very simple assumptions based on real undulator source calaculations (see RAY-UI). 

In SHADOW such a source is called "Gaussian Undulator", we could also call it that and check in this course whether we really simulate a Gaussian beam with our point source, see the following publication:

[https://pubs.aip.org/aapt/ajp/article/74/8/722/1032407/Representation-of-a-Gaussian-beam-by-rays](https://pubs.aip.org/aapt/ajp/article/74/8/722/1032407/Representation-of-a-Gaussian-beam-by-rays)

**Comment by Atraxus** [comment]
Todo: create Issues from this feature request
