### ISSUE TITLE
Fix: building on windows in CI

### ISSUE THREAD

**Issue by ichinii** [hz-b/rayx#310]
building on windows currently does not work in CI. probably does not work on any windows machine right now.

related PR: https://github.com/hz-b/rayx/pull/319

**Comment by Atraxus** [comment]
Not finding the CUDA compiler looks like a CI issue to me. Why do you think other Windows machines might be affected as well?

**Comment by ichinii** [comment]
the current work on a fix is on branch [alpaka.merge2.cuda](https://github.com/hz-b/rayx/tree/alpaka.merge2.cuda)
the last CI run can be seen here <https://github.com/hz-b/rayx/actions/runs/10177229764>

**Comment by Atraxus** [comment]
Looks like the Cuda 12.5 bug we encountered previously I think
