### ISSUE TITLE
Multiple precision modes (16, 32, 64, 128 - Bit)

### ISSUE THREAD

**Issue by Atraxus** [hz-b/rayx#33]
Idea for future feature to cater to more people. We need to discuss the cost vs reward ratio for this feature.

**Comment by EnricoAhlers** [comment]
Regarding numerical instability:
When using float instead of double values and thus cos instead of r8_cos the accuracy of some tests needs to be lowered. E.g. for RZPs from 1e-7 to 1e-5.
When also using sin instead of r8_sin and atan instead of r8_atan the accuracy needs to be set to 1e-4.

**Comment by Atraxus** [comment]
Further Testing: Replace each double, glm::dvec3, etc. with float, glm::vec3, etc.

**Comment by EnricoAhlers** [comment]
https://www.reddit.com/r/vulkan/comments/16shhea/vkfft_now_supports_quad_precision_doubledouble/

**Comment by EnricoAhlers** [comment]
<img width="939" alt="image" src="https://github.com/hz-b/rayx/assets/4237050/d16edb1f-33af-435b-81bb-090a8c774d8a">

32 bit seems a bit (heh) faster

**Comment by EnricoAhlers** [comment]
<img width="942" alt="image" src="https://github.com/hz-b/rayx/assets/4237050/c582e874-8296-46a4-a932-b35bdafe7459">

Also workgroup_size of 8 instead of 32 is much faster. I just pushed this to development.

**Comment by EnricoAhlers** [comment]
Further testing: Multithreaded trace():
35s runtime

Usually:
50s runtime

Sadly the instrumentor currently doesn't work with multithreading

**Comment by EnricoAhlers** [comment]
We had the theory that 32 bit could be a lot faster than 64 bit as standard function like sin() could be used. We saw that it's only a bit faster and is not worth the trade-offs.
